# Generated by Django 4.2.7 on 2023-11-30 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Endereço de E-mail')),
                ('telefone', models.TextField(max_length=14, verbose_name='Telefone')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60, verbose_name='Código do vendedor')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do vendedor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Endereço de E-mail')),
                ('telefone', models.TextField(max_length=14, verbose_name='Telefone')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nome'],
            },
        ),
    ]
