# Generated by Django 4.2.7 on 2023-11-30 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfDiaSemana',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_da_semana', models.CharField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, unique=True, verbose_name='Dia da semana')),
                ('valor_minimo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentual de comissão mínimo')),
                ('valor_maximo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentual de comissão máximo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'ordering': ['dia_da_semana'],
            },
        ),
    ]
